config:
  server: irc.beirut.com
  port	: 6667
  realname: quotebot
  nick	: child
  default_channel: "#tl_test"
  default_admin	: myircusername

commands:
  test: "look there http://example.com"
  another test: "hello world"
