config:
  server: irc.server.com
  port	: 6667
  realname: quotebot
  nick	: quotebot
  default_channel: "#quotebot_test"
  default_admin	: myircusername

commands:
  test: "look there http://example.com"
  another test: "hello world"
