greetings:
  badChance: 5
  bad:
    - "fuck you, you fucking fuck"
    - "http://images.t-nation.com/forum_images/auto/r/350x0/4/a/4a4da-Ari_Gold_Get_the_Fuck_Out.gif"
  goodChance: 10
  good:
    - "hy sweety"